sqlx と tokio のバージョンアップ
cafecoder-dev/cafecoder-rs pull request #14
Opened 2021-02-25 11:15 UTC by earlgray283

sqlx が 0.5.1 になったのでそれに伴って tokio も 1.2.0 にバージョンアップしました。

2021-02-25 11:41 UTC, magurotuna requested changes
いくつか直さないとコンパイルが通らなそうなので、お手数ですが修正お願いします:pray:

2021-02-25 12:19 UTC, earlgray283 commented
ノーチェックで PR 出して本当にすみませんでした

2021-02-25 12:25 UTC, earlgray283 commented
tokio が `1.2.0` にバージョンアップした際に `delay_for` がなくなってしまったようですね・・・。
`delay_for` で指定した時間分待つならば、`sleep` で代替ができるでしょうか。

2021-02-25 13:51 UTC, magurotuna commented
tokio 0.3 から `sleep` という名前に変わったみたいです。
動作としては同じはずなので、機械的に `sleep` に置き換えるので良いかなと思います。

2021-02-26 08:46 UTC, earlgray283 commented
clippy 通しました。
先にこの pr 出して、他の pr もそれに合わせて変更する形にして良いですか？

2021-02-26 10:34 UTC, magurotuna requested changes

2021-02-26 10:34 UTC, magurotuna commented on Cargo.toml
>  # TODO(magurotuna): Upgrade tokio to v1 after sqlx gets compatible with that
このTODO消しちゃってください 🙆‍♂️

2021-02-26 10:34 UTC, magurotuna commented
> 先にこの pr 出して、他の pr もそれに合わせて変更する形にして良いですか？

良いと思います！

2021-02-28 08:19 UTC, earlgray283 commented
消しておきました。特に問題なければ merge しちゃいます。

2021-02-28 08:39 UTC, magurotuna approved these changes
ありがとうございます 🙆

2021-02-28 09:12 UTC, merged